// <auto-generated />
namespace ForumCoderASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(created));
        
        string IMigrationMetadata.Id
        {
            get { return "202111050351446_created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
